[package]
name = "tower-abci"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tendermint-proto = { git = "https://github.com/hdevalence/tendermint-rs.git", branch = "abci-domain-types" }
tendermint = { git = "https://github.com/hdevalence/tendermint-rs.git", branch = "abci-domain-types" }
# tendermint-proto = { path = "../tendermint-rs/proto" }
# tendermint = { path = "../tendermint-rs/tendermint" }
bytes = "1"
tokio = { version = "1", features = ["full"]}
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1"
tower = { version = "0.4", features = ["full"]}
pin-project = "1"
futures = "0.3"
tracing = "0.1"
prost = "0.7"
tracing-tower = { git = "https://github.com/tokio-rs/tracing/", branch = "v0.1.x" }

[dev-dependencies]
structopt = "0.3"
tracing-subscriber = "0.2"

[features]
doc = []

[patch.crates-io]
tracing = { git = "https://github.com/tokio-rs/tracing/", branch = "v0.1.x" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing/", branch = "v0.1.x" }